CXX = g++
CXXFLAGS = -std=c++17 -O2 -pthread

all: prime-calculator

prime-calculator: prime-calculator.cpp
	$(CXX) $(CXXFLAGS) -o prime-calculator prime-calculator.cpp

clean:
	rm -f prime-calculator
